# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    github_authenticator:
        class: AppBundle\Security\GithubAuthenticator
        arguments: ["@csa_guzzle.client.github_oauth", "%github.client_id%", "%github.client_secret%", "@router"]

    github_user_provider:
        class: AppBundle\Security\GithubUserProvider
        arguments: ["@csa_guzzle.client.github_api"]
